### ISSUE TITLE
Missing main.css

### ISSUE THREAD

**Issue by ericmasiello** [hojberg/mastering-react#12]
Main.css file seems to be missing. Think you could add it?

**Comment by ericmasiello** [comment]
Just noticed you have scss setup in the styles directory. my bad!

**Comment by badc0ded** [comment]
For anyone else who ran into this, and wasn't able to make it work with just @ericmasiello mention of scss, here's what I did. 

At 2:13 into the Building a Solid Foundation video you can see that the build command was changed to: `"browserify src/main.js -t babelify --outfile public/bundle.js && node-sass --output-style compressed styles/main.scss public/main.css"` In order to use node-sass if you don't have it installed, you'll have to  add it with `npm install --save node-sass` then update the build command in package.json to reflect the node-sass change. then build and refresh and you should be all set.
